//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhakhoaMyNgoc.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIzaSyA6sSny_HGleBulaMnPbJ7GFOKUJMZyVS4")]
        public string FirebaseAPIKey {
            get {
                return ((string)(this["FirebaseAPIKey"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RGVtb1Bhc3N3b3JkMTIzQA==")]
        public string FirebaseAuthPassword {
            get {
                return ((string)(this["FirebaseAuthPassword"]));
            }
            set {
                this["FirebaseAuthPassword"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=")]
        public string FirebaseSignInAPI {
            get {
                return ((string)(this["FirebaseSignInAPI"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://nhakhoamyngoc-dev-default-rtdb.asia-southeast1.firebasedatabase.app/{node" +
            "}.json?auth={idToken}")]
        public string FirebaseRestApi {
            get {
                return ((string)(this["FirebaseRestApi"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("duy.buiphankhanh@gmail.com")]
        public string FirebaseAuthEmail {
            get {
                return ((string)(this["FirebaseAuthEmail"]));
            }
            set {
                this["FirebaseAuthEmail"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Host=ep-quiet-brook-a1l7ctt8-pooler.ap-southeast-1.aws.neon.tech;Port=5432;Databa" +
            "se=neondb;Username=neondb_owner;Password=npg_DKtAe2O1dqRr;Ssl Mode=Require;Trust" +
            " Server Certificate=true")]
        public string DatabaseConnectionString {
            get {
                return ((string)(this["DatabaseConnectionString"]));
            }
        }
    }
}
